services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: solar_api
    ports:
      - "8002:8002"
    volumes:
      - .:/app

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    container_name: solar_dashboard
    ports:
      - "8501:8501"
    depends_on:
      - api
    volumes:
      - .:/app
    environment:
      - API_URL=http://api:8002
